application: oauth-profile
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /oauth/v1/userinfo
  script: handlers.userinfo.app
  secure: always

- url: /oauth/v2/userinfo
  script: handlers.userinfo.app
  secure: always

- url: /
  script: handlers.home.app
  secure: always

- url: /robots.txt
  script: handlers.robots.app

- url: /.*
  script: handlers.notfound.app
