application: oauth-profile
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /oauth/v1/userinfo
  script: userinfo.app
  secure: always

- url: /
  script: home.app
  secure: always
